<?php
// Autogenerated from composer.json - All changes will be overridden if generated again!

require_once __DIR__ . "/vendor/autoload.php";

$id = "xlpa";
$version = "0.1.0";
$ilias_min_version = "6.0";
$ilias_max_version = "7.999";
$responsible = "Robert";
$responsible_mail = "support@fluxlabs.ch";
