<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\LearningPath\Utils\LearningPathTrait;
use srag\DIC\LearningPath\DICTrait;

/**
 * Class ilObjLearningPathListGUI
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author Robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilObjLearningPathListGUI extends ilObjectPluginListGUI
{

    use DICTrait;
    use LearningPathTrait;

    const PLUGIN_CLASS_NAME = ilLearningPathPlugin::class;


    /**
     * ilObjLearningPathListGUI constructor
     *
     * @param int $a_context
     */
    public function __construct()
    {
        parent::__construct();

        $dic = $this->getDIC();
        $obj_type = ilObjLearningPath::OBJ_TYPE;
        $this->lng = $dic->language();
        $this->lng->loadLanguageModule($obj_type);
    }

    protected function getDIC() : ILIAS\DI\Container
    {
        global $DIC;
        return $DIC;
    }


    /**
     * @inheritDoc
     */
    public function getGuiClass() : string
    {
        return ilObjLearningPathGUI::class;
    }


    /**
     * @inheritDoc
     */
    public function getProperties() : array
    {
        $props = parent::getProperties();

        if (ilObjLearningPathAccess::isOffline($this->ref_id)) {
            $props[] = array("alert" => true, "property" => $this->lng->txt("status"),
                "value" => $this->lng->txt("offline"));
        }

        return $props;
    }


    /**
     * @inheritDoc
     */
    public function initCommands() : array
    {
        $this->static_link_enabled = true;
        $this->delete_enabled = true;
        $this->cut_enabled = true;
        $this->info_screen_enabled = true;
        $this->copy_enabled = true;
        $this->subscribe_enabled = false;
        $this->link_enabled = true;
        $this->gui_class_name = "ilobjlearningpathgui";
        $this->type = ilObjLearningPath::OBJ_TYPE;
        $this->commands = ilObjLearningPathAccess::_getCommands();
    }


    /**
     * @inheritDoc
     */
    public function initType() : void
    {
        $this->setType(ilLearningPathPlugin::PLUGIN_ID);
    }
}
