<?php

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\LearningPath\Utils\LearningPathTrait;
use ILIAS\DI\Container;
use srag\CustomInputGUIs\LearningPath\Loader\CustomInputGUIsLoaderDetector;
use srag\DevTools\LearningPath\DevToolsCtrl;
use srag\RemovePluginDataConfirm\LearningPath\RepositoryObjectPluginUninstallTrait;

/**
 * Class ilLearningPathPlugin
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @author Robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
class ilLearningPathPlugin extends ilRepositoryObjectPlugin
{

    use RepositoryObjectPluginUninstallTrait;
    use LearningPathTrait;

    const PLUGIN_CLASS_NAME = self::class;
    const PLUGIN_ID = "xlpa";
    const PLUGIN_NAME = "LearningPath";
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * ilLearningPathPlugin constructor
     */
    public function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @inheritDoc
     */
    public function exchangeUIRendererAfterInitialization(Container $dic) : Closure
    {
        return CustomInputGUIsLoaderDetector::exchangeUIRendererAfterInitialization();
    }


    /**
     * @inheritDoc
     */
    public function getPluginName() : string
    {
        return self::PLUGIN_NAME;
    }


    /**
     * @inheritDoc
     */
    public function updateLanguages(/*?array*/ $a_lang_keys = null) : void
    {
        parent::updateLanguages($a_lang_keys);

        $this->installRemovePluginDataConfirmLanguages();

        DevToolsCtrl::installLanguages(self::plugin());
    }


    /**
     * @inheritDoc
     */
    protected function deleteData() : void
    {
        self::learningPath()->dropTables();
    }


    /**
     * @inheritDoc
     */
    protected function shouldUseOneUpdateStepOnly() : bool
    {
        return false;
    }
}
