<?php

namespace srag\Plugins\LearningPath\Config;

use srag\Plugins\LearningPath\Config\Form\FormBuilder;
use srag\Plugins\LearningPath\Utils\LearningPathTrait;
use ilLearningPathPlugin;
use srag\ActiveRecordConfig\LearningPath\Config\AbstractFactory;

/**
 * Class Factory
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\LearningPath\Config
 *
 * @author Robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Factory extends AbstractFactory
{

    use LearningPathTrait;

    const PLUGIN_CLASS_NAME = ilLearningPathPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Factory constructor
     */
    protected function __construct()
    {
        parent::__construct();
    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @param ConfigCtrl $parent
     *
     * @return FormBuilder
     */
    public function newFormBuilderInstance(ConfigCtrl $parent) : FormBuilder
    {
        $form = new FormBuilder($parent);

        return $form;
    }
}
