<?php

namespace srag\Plugins\LearningPath\Utils;

use srag\Plugins\LearningPath\Repository;

/**
 * Trait LearningPathTrait
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\LearningPath\Utils
 *
 * @author Robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
trait LearningPathTrait
{

    /**
     * @return Repository
     */
    protected static function learningPath() : Repository
    {
        return Repository::getInstance();a
    }
}
