<?php

namespace srag\Plugins\learningpath\Utils;

use srag\Plugins\learningpath\Repository;

/**
 * Trait LearningpathTrait
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\learningpath\Utils
 *
 * @author robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
trait LearningpathTrait
{

    /**
     * @return Repository
     */
    protected static function learningpath() : Repository
    {
        return Repository::getInstance();
    }
}
