<?php

namespace srag\Plugins\LearningPath;

use srag\Plugins\LearningPath\Config\Repository as ConfigRepository;
use srag\Plugins\LearningPath\ObjectSettings\Repository as ObjectSettingsRepository;
use srag\Plugins\LearningPath\Utils\LearningPathTrait;
use ilLearningPathPlugin;
use srag\DIC\LearningPath\DICTrait;

/**
 * Class Repository
 *
 * Generated by SrPluginGenerator v2.9.1
 *
 * @package srag\Plugins\LearningPath
 *
 * @author Robert <support@fluxlabs.ch>
 * @author fluxlabs <support@fluxlabs.ch>
 */
final class Repository
{

    use DICTrait;
    use LearningPathTrait;

    const PLUGIN_CLASS_NAME = ilLearningPathPlugin::class;
    /**
     * @var self|null
     */
    protected static $instance = null;


    /**
     * Repository constructor
     */
    private function __construct()
    {

    }


    /**
     * @return self
     */
    public static function getInstance() : self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }


    /**
     * @return ConfigRepository
     */
    public function config() : ConfigRepository
    {
        return ConfigRepository::getInstance();
    }


    /**
     *
     */
    public function dropTables() : void
    {
        $this->config()->dropTables();
        $this->objectSettings()->dropTables();
    }


    /**
     *
     */
    public function installTables() : void
    {
        $this->config()->installTables();
        $this->objectSettings()->installTables();
    }


    /**
     * @return ObjectSettingsRepository
     */
    public function objectSettings() : ObjectSettingsRepository
    {
        return ObjectSettingsRepository::getInstance();
    }
}
